import type { Category, IncomeCategory } from '@/lib/types';

export type TransactionEntryType = 'expense' | 'income';

export const EXPENSE_VERBS = [
  'spent',
  'spend',
  'pay',
  'paid',
  'bought',
  'used',
  'ordered',
  'purchased',
  'nag spend',
  'nagspend',
  'nag bayad',
  'nagbayad',
  'gumastos',
  'kumain',
  'binili',
  'bayad',
] as const;

export const INCOME_VERBS = [
  'received',
  'earned',
  'got',
  'made',
  'allowance',
  'sweldo',
  'sahod',
  'raket',
  'sideline',
  'padala',
] as const;

export const TYPE_REPLY_ALIASES: Record<TransactionEntryType, string[]> = {
  expense: ['expense', 'log as expense', 'as expense', 'make it expense'],
  income: ['income', 'log as income', 'as income', 'make it income'],
};

export const YES_REPLIES = new Set([
  'yes',
  'yeah',
  'yep',
  'confirm',
  'go',
  'log it',
  'save it',
  'okay',
  'ok',
]);

export const CONNECTORS = /\s*(?:,|;|\n| then | tapos | plus | & )\s*/i;

export const WEEKDAY_INDEX: Record<string, number> = {
  sunday: 0,
  linggo: 0,
  monday: 1,
  lunes: 1,
  tuesday: 2,
  martes: 2,
  wednesday: 3,
  miyerkules: 3,
  mierkules: 3,
  thursday: 4,
  huwebes: 4,
  friday: 5,
  biyernes: 5,
  saturday: 6,
  sabado: 6,
};

export const STOP_WORDS = new Set([
  'spent',
  'spend',
  'pay',
  'paid',
  'bought',
  'used',
  'ordered',
  'purchased',
  'received',
  'earned',
  'got',
  'made',
  'expense',
  'income',
  'log',
  'as',
  'on',
  'for',
  'from',
  'my',
  'the',
  'a',
  'an',
  'to',
  'into',
  'at',
  'sa',
  'ako',
  'nag',
  'nagspend',
  'nagbayad',
  'ng',
  'ko',
  'kahapon',
  'kanina',
  'today',
  'yesterday',
  'last',
  'night',
  'this',
  'morning',
  'by',
  'using',
  'via',
  'through',
  'transfer',
  'move',
  'send',
  'save',
  'saved',
  'deposit',
  'withdraw',
  'lent',
  'borrowed',
  'paid',
  'back',
  'me',
  'lang',
  'mga',
  'around',
  'about',
  'roughly',
  'approximately',
  'halos',
  'approx',
  'may',
  'utang',
  'kay',
  'ki',
  'si',
  'ni',
  'sakin',
  'akin',
  'sa',
  'akin',
  'ng',
]);

export const STARTER_QUICK_REPLIES = ['Log expense', 'Log income', 'Move money', 'Track utang'] as const;

export const DEFAULT_EXPENSE_CATEGORY: Category = 'Miscellaneous';
export const DEFAULT_INCOME_CATEGORY: IncomeCategory = 'Other Income';
