export const CATEGORIES = [
  'Food',
  'Transportation',
  'Subscriptions',
  'Utilities',
  'Shopping',
  'Entertainment',
  'Health',
  'Education',
  'Miscellaneous',
] as const;

export type Category = (typeof CATEGORIES)[number];

export type TransactionType = 'expense' | 'income' | 'savings';

export type IncomeCategory =
  | 'Freelance'
  | 'Side Job'
  | 'Salary'
  | 'Part-time'
  | 'Bonus'
  | 'Refund'
  | 'Gift'
  | 'Other Income';

export const INCOME_CATEGORIES: IncomeCategory[] = [
  'Freelance',
  'Side Job',
  'Salary',
  'Part-time',
  'Bonus',
  'Refund',
  'Gift',
  'Other Income',
];

export const PAYMENT_METHODS = [
  'Cash',
  'Credit Card',
  'Debit Card',
  'GCash',
  'Maya',
  'Bank Transfer',
  'Other',
] as const;

export type PaymentMethod = (typeof PAYMENT_METHODS)[number];

export const ACCOUNT_TYPES = ['Cash', 'Bank', 'E-Wallet', 'Other'] as const;
export type AccountType = (typeof ACCOUNT_TYPES)[number];

export const RECURRING_FREQUENCIES = [
  'daily',
  'weekly',
  'monthly',
  'yearly',
] as const;

export type RecurringFrequency = (typeof RECURRING_FREQUENCIES)[number];

export interface RecurringConfig {
  frequency: RecurringFrequency;
  interval: number;
  nextRunDate: string; // ISO string
  endDate?: string; // ISO string
}

export interface TransactionSplit {
  id: string;
  category: Category;
  subCategory?: string;
  amount: number;
}

export interface TransactionSplitInput {
  id?: string;
  category: Category;
  subCategory?: string;
  amount: number;
}

export interface SavingsTransactionMeta {
  goalId: string;
  goalName: string;
  depositType: 'deposit' | 'withdrawal';
}

export interface Transaction {
  id: string;
  amount: number;
  type: TransactionType;
  incomeCategory?: IncomeCategory;
  category: Category;
  subCategory?: string;
  merchant?: string;
  description?: string;
  date: string; // ISO string
  paymentMethod: PaymentMethod;
  notes?: string;
  tags?: string[];
  attachmentBase64?: string;
  split?: TransactionSplit[];
  recurring?: RecurringConfig;
  recurringOriginId?: string;
  isAutoGenerated?: boolean;
  accountId?: string;
  transferGroupId?: string;
  linkedTransferGroupId?: string;
  metadata?: Record<string, unknown>;
  savingsMeta?: SavingsTransactionMeta;
  createdAt: string;
  updatedAt: string;
  synced?: boolean;
}

export interface Account {
  id: string;
  userId: string;
  name: string;
  type: AccountType;
  initialBalance: number;
  color?: string;
  icon?: string;
  isSystemCashWallet?: boolean;
  isArchived: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface AccountWithBalance extends Account {
  computedBalance: number;
}

export interface Budget {
  id: string;
  category: Category | 'Overall';
  subCategory?: string;
  monthlyLimit: number;
  month: string; // YYYY-MM
  rollover?: boolean;
  alertThresholdsTriggered?: number[];
}

export interface BudgetInput {
  id?: string;
  category: Category | 'Overall';
  subCategory?: string;
  monthlyLimit: number;
  month: string;
  rollover?: boolean;
  alertThresholdsTriggered?: number[];
}

export interface Subscription {
  id: string;
  name: string;
  amount: number;
  billingCycle: 'weekly' | 'monthly' | 'yearly';
  lastDetected: string;
  category: Category;
}

export interface TimelineEvent {
  id: string;
  eventType:
    | 'started_tracking'
    | 'subscription_detected'
    | 'spending_spike'
    | 'highest_savings'
    | 'budget_exceeded'
    | 'milestone'
    | 'spending_improvement'
    | 'savings_streak'
    | 'savings_milestone'
    | 'best_savings_rate'
    | 'low_spend_month';
  description: string;
  date: string;
  metadata: Record<string, unknown>;
  context?: string;   // human-readable explanation of what happened
  advice?: string;    // actionable recommendation
  link?: string;      // drill-down URL (e.g., /transactions?month=2025-03)
  severity?: 'positive' | 'neutral' | 'warning' | 'critical';
  amount?: number;    // optional monetary highlight
}

export type InsightType =
  | 'spending_spike'
  | 'subscription'
  | 'budget_risk'
  | 'pattern'
  | 'saving'
  | 'budget_burn_rate'
  | 'biggest_expense'
  | 'category_concentration'
  | 'week_comparison'
  | 'no_spend_days'
  | 'essentials_ratio'
  | 'avg_transaction_size'
  | 'payment_method_split'
  | 'weekend_vs_weekday'
  | 'category_drift'
  | 'month_end_projection'
  | 'subscription_creep'
  | 'savings_rate_trend'
  | 'post_income_behavior'
  | 'best_month_replay';

export interface Insight {
  id: string;
  insightType: InsightType;
  title: string;
  message: string;
  severity: 'info' | 'warning' | 'critical';
  category?: Category;
  createdAt: string;
  tier: 1 | 2 | 3;
  requiresTransactionCount: number;
  dataPayload?: Record<string, unknown>;
}

export interface BudgetStatus {
  budgetId: string;
  category: Category | 'Overall';
  subCategory?: string;
  baseLimit: number;
  limit: number;
  incomeBoost: number;
  effectiveLimit: number;
  rolloverCarry: number;
  spent: number;
  remaining: number;
  percentage: number;
  projectedSpent: number;
  projectedOverage: number;
  status: 'safe' | 'warning' | 'critical';
}

export interface BudgetThresholdAlert {
  id: string;
  budgetId: string;
  month: string;
  category: Category | 'Overall';
  subCategory?: string;
  threshold: 50 | 80 | 100;
  spent: number;
  limit: number;
  percentage: number;
  message: string;
}

export interface DashboardData {
  totalSpentThisMonth: number;
  totalSpentLastMonth: number;
  totalBalance: number;
  remainingBudget: number;
  monthlyBudget: number;
  savingsRate: number;
  expenseGrowthRate: number;
  budgetStatuses: BudgetStatus[];
  budgetAlerts: BudgetThresholdAlert[];
  categoryBreakdown: { category: string; amount: number }[];
  weeklySpending: { week: string; amount: number }[];
  dailySpending: { day: string; amount: number }[];
  calendarSpending: { date: string; amount: number }[];
  currentMonthTransactions: Transaction[];
  recentTransactions: Transaction[];
  insights: Insight[];
}

export interface MonthlySavings {
  month: string; // YYYY-MM
  budget: number;
  spent: number;
  saved: number;
  savingsRate: number; // percentage
  cumulative: number;  // running total of all saved amounts
}

export interface TransactionInput {
  amount: number;
  type?: TransactionType;
  accountId?: string;
  linkedTransferGroupId?: string;
  incomeCategory?: IncomeCategory;
  category: Category;
  subCategory?: string;
  merchant?: string;
  description?: string;
  date?: string;
  paymentMethod?: PaymentMethod;
  notes?: string;
  tags?: string[];
  attachmentBase64?: string;
  metadata?: Record<string, unknown>;
  split?: TransactionSplitInput[];
  recurring?: {
    frequency: RecurringFrequency;
    interval?: number;
    endDate?: string;
  };
}

export type ExternalWithdrawalStatus = 'pending' | 'completed' | 'failed' | 'cancelled';

export interface ExternalWithdrawalRequest {
  id: string;
  userId: string;
  fromAccountId: string;
  amount: number;
  feeAmount: number;
  netAmount: number;
  destinationSummary: string;
  status: ExternalWithdrawalStatus;
  providerRef?: string;
  etaAt?: string;
  idempotencyKey: string;
  failureReason?: string;
  completedTransactionId?: string;
  metadata?: Record<string, unknown>;
  createdBy?: string;
  createdAt: string;
  updatedAt: string;
}

export type DebtDirection = 'owed' | 'owing';
export type DebtStatus = 'active' | 'settled';

export interface Debt {
  id: string;
  userId: string;
  direction: DebtDirection;
  personName: string;
  amount: number;
  reason: string;
  date: string; // YYYY-MM-DD
  status: DebtStatus;
  settledAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface DebtInput {
  direction: DebtDirection;
  personName: string;
  amount: number;
  reason: string;
  date?: string;
}

export type SavingsGoalStatus = 'active' | 'completed' | 'archived';
export type SavingsDepositType = 'deposit' | 'withdrawal';

export type SavingsGoalHealth = 'on_track' | 'falling_behind' | 'at_risk' | 'no_deadline';

export interface SavingsGoal {
  id: string;
  userId: string;
  name: string;
  emoji: string;
  colorAccent: string;
  tag?: string;
  motivationNote?: string;
  targetAmount: number;
  currentAmount: number;
  deadline?: string; // ISO date string YYYY-MM-DD
  isPrivate: boolean;
  isPinned: boolean;
  sortOrder: number;
  status: SavingsGoalStatus;
  completedAt?: string;
  whatDidYouBuy?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SavingsDeposit {
  id: string;
  goalId: string;
  userId: string;
  amount: number;
  type: SavingsDepositType;
  note?: string;
  createdAt: string;
}

export interface SavingsGoalWithDeposits extends SavingsGoal {
  deposits: SavingsDeposit[];
  progressPercent: number;
  health: SavingsGoalHealth;
  projectedCompletionDate?: string; // ISO date string
  requiredMonthlyAmount?: number;
  milestones: SavingsGoalMilestone[];
}

export interface SavingsGoalMilestone {
  percent: 25 | 50 | 75 | 100;
  hitAt?: string; // ISO date string - undefined if not yet hit
}

export interface SavingsGoalInput {
  name: string;
  emoji: string;
  colorAccent: string;
  tag?: string;
  motivationNote?: string;
  targetAmount: number;
  deadline?: string;
  isPrivate?: boolean;
  isPinned?: boolean;
}

export interface SavingsDepositInput {
  goalId: string;
  amount: number;
  type: SavingsDepositType;
  note?: string;
}

export interface SavingsGoalsSummary {
  goals: SavingsGoalWithDeposits[];
  totalSaved: number;
  activeGoalCount: number;
  closestGoal?: SavingsGoalWithDeposits;
  nearestDeadlineGoal?: SavingsGoalWithDeposits;
  savingsRate: number;
}
