export const CATEGORIES = [
  'Food',
  'Transportation',
  'Subscriptions',
  'Utilities',
  'Shopping',
  'Entertainment',
  'Health',
  'Education',
  'Miscellaneous',
] as const;

export type Category = (typeof CATEGORIES)[number];

export type TransactionType = 'expense' | 'income';

export type IncomeCategory =
  | 'Freelance'
  | 'Side Job'
  | 'Salary'
  | 'Part-time'
  | 'Bonus'
  | 'Refund'
  | 'Gift'
  | 'Other Income';

export const INCOME_CATEGORIES: IncomeCategory[] = [
  'Freelance',
  'Side Job',
  'Salary',
  'Part-time',
  'Bonus',
  'Refund',
  'Gift',
  'Other Income',
];

export const PAYMENT_METHODS = [
  'Cash',
  'Credit Card',
  'Debit Card',
  'GCash',
  'Maya',
  'Bank Transfer',
  'Other',
] as const;

export type PaymentMethod = (typeof PAYMENT_METHODS)[number];

export const RECURRING_FREQUENCIES = [
  'daily',
  'weekly',
  'monthly',
  'yearly',
] as const;

export type RecurringFrequency = (typeof RECURRING_FREQUENCIES)[number];

export interface RecurringConfig {
  frequency: RecurringFrequency;
  interval: number;
  nextRunDate: string; // ISO string
  endDate?: string; // ISO string
}

export interface TransactionSplit {
  id: string;
  category: Category;
  subCategory?: string;
  amount: number;
}

export interface TransactionSplitInput {
  id?: string;
  category: Category;
  subCategory?: string;
  amount: number;
}

export interface Transaction {
  id: string;
  amount: number;
  type: TransactionType;
  incomeCategory?: IncomeCategory;
  category: Category;
  subCategory?: string;
  merchant?: string;
  description?: string;
  date: string; // ISO string
  paymentMethod: PaymentMethod;
  notes?: string;
  tags?: string[];
  attachmentBase64?: string;
  split?: TransactionSplit[];
  recurring?: RecurringConfig;
  recurringOriginId?: string;
  isAutoGenerated?: boolean;
  createdAt: string;
  updatedAt: string;
  synced?: boolean;
}

export interface Budget {
  id: string;
  category: Category | 'Overall';
  subCategory?: string;
  monthlyLimit: number;
  month: string; // YYYY-MM
  rollover?: boolean;
  alertThresholdsTriggered?: number[];
}

export interface BudgetInput {
  id?: string;
  category: Category | 'Overall';
  subCategory?: string;
  monthlyLimit: number;
  month: string;
  rollover?: boolean;
  alertThresholdsTriggered?: number[];
}

export interface Subscription {
  id: string;
  name: string;
  amount: number;
  billingCycle: 'weekly' | 'monthly' | 'yearly';
  lastDetected: string;
  category: Category;
}

export interface TimelineEvent {
  id: string;
  eventType:
    | 'started_tracking'
    | 'subscription_detected'
    | 'spending_spike'
    | 'highest_savings'
    | 'budget_exceeded'
    | 'milestone'
    | 'spending_improvement'
    | 'savings_streak'
    | 'savings_milestone'
    | 'best_savings_rate'
    | 'low_spend_month';
  description: string;
  date: string;
  metadata: Record<string, unknown>;
  context?: string;   // human-readable explanation of what happened
  advice?: string;    // actionable recommendation
  link?: string;      // drill-down URL (e.g., /transactions?month=2025-03)
  severity?: 'positive' | 'neutral' | 'warning' | 'critical';
  amount?: number;    // optional monetary highlight
}

export interface Insight {
  id: string;
  insightType: 'spending_spike' | 'subscription' | 'budget_risk' | 'pattern' | 'saving';
  message: string;
  severity: 'info' | 'warning' | 'critical';
  category?: Category;
  createdAt: string;
}

export interface BudgetStatus {
  budgetId: string;
  category: Category | 'Overall';
  subCategory?: string;
  baseLimit: number;
  limit: number;
  incomeBoost: number;
  effectiveLimit: number;
  rolloverCarry: number;
  spent: number;
  remaining: number;
  percentage: number;
  projectedSpent: number;
  projectedOverage: number;
  status: 'safe' | 'warning' | 'critical';
}

export interface BudgetThresholdAlert {
  id: string;
  budgetId: string;
  month: string;
  category: Category | 'Overall';
  subCategory?: string;
  threshold: 50 | 80 | 100;
  spent: number;
  limit: number;
  percentage: number;
  message: string;
}

export interface DashboardData {
  totalSpentThisMonth: number;
  totalSpentLastMonth: number;
  remainingBudget: number;
  monthlyBudget: number;
  savingsRate: number;
  expenseGrowthRate: number;
  budgetStatuses: BudgetStatus[];
  budgetAlerts: BudgetThresholdAlert[];
  categoryBreakdown: { category: string; amount: number }[];
  weeklySpending: { week: string; amount: number }[];
  dailySpending: { day: string; amount: number }[];
  recentTransactions: Transaction[];
  insights: Insight[];
}

export interface MonthlySavings {
  month: string; // YYYY-MM
  budget: number;
  spent: number;
  saved: number;
  savingsRate: number; // percentage
  cumulative: number;  // running total of all saved amounts
}

export interface TransactionInput {
  amount: number;
  type?: TransactionType;
  incomeCategory?: IncomeCategory;
  category: Category;
  subCategory?: string;
  merchant?: string;
  description?: string;
  date?: string;
  paymentMethod?: PaymentMethod;
  notes?: string;
  tags?: string[];
  attachmentBase64?: string;
  split?: TransactionSplitInput[];
  recurring?: {
    frequency: RecurringFrequency;
    interval?: number;
    endDate?: string;
  };
}
