import type {
  Account,
  Budget,
  ExternalWithdrawalRequest,
  RecurringConfig,
  SavingsDeposit,
  SavingsGoal,
  Transaction,
  TransactionSplit,
} from '../types';

import type {
  AccountRow,
  BudgetRow,
  ExternalWithdrawalRequestRow,
  SavingsDepositRow,
  SavingsGoalRow,
  TransactionRow,
  TransactionSplitRow,
} from './rows';
import {
  normalizeAccountType,
  normalizeIncomeCategory,
  normalizeMetadata,
  normalizeSavingsTransactionMeta,
  normalizeTransactionType,
} from './normalizers';
import { dateToMonth, normalizeIsoDate, toNumber } from './shared';

export function toTransactionSplit(row: TransactionSplitRow): TransactionSplit {
  return {
    id: row.id,
    category: row.category,
    subCategory: row.sub_category ?? undefined,
    amount: toNumber(row.amount),
  };
}

export function toRecurring(row: TransactionRow): RecurringConfig | undefined {
  if (!row.recurring_frequency || !row.recurring_next_run_at) {
    return undefined;
  }

  return {
    frequency: row.recurring_frequency,
    interval: Math.max(1, Math.floor(row.recurring_interval ?? 1)),
    nextRunDate: normalizeIsoDate(row.recurring_next_run_at, row.transaction_at),
    endDate: row.recurring_end_at
      ? normalizeIsoDate(row.recurring_end_at, row.recurring_end_at)
      : undefined,
  };
}

export function toTransaction(row: TransactionRow): Transaction {
  const split = Array.isArray(row.transaction_splits)
    ? row.transaction_splits.map(toTransactionSplit)
    : [];
  const type = normalizeTransactionType(row.type);
  const persistedSubCategory = row.sub_category ?? undefined;
  const incomeCategory =
    type === 'income'
      ? normalizeIncomeCategory(persistedSubCategory) ?? 'Other Income'
      : undefined;
  const savingsMeta =
    type === 'savings'
      ? normalizeSavingsTransactionMeta(row.savings_meta)
      : undefined;

  return {
    id: row.id,
    amount: toNumber(row.amount),
    type,
    incomeCategory,
    category: row.category,
    subCategory: type === 'expense' ? persistedSubCategory : undefined,
    merchant: row.merchant ?? undefined,
    description: row.description,
    date: normalizeIsoDate(row.transaction_at, row.transaction_at),
    paymentMethod: row.payment_method,
    notes: row.notes || '',
    tags: Array.isArray(row.tags) ? row.tags : [],
    attachmentBase64: row.attachment_base64 ?? undefined,
    savingsMeta,
    split: split.length > 0 ? split : undefined,
    recurring: toRecurring(row),
    recurringOriginId: row.recurring_origin_id ?? undefined,
    isAutoGenerated: row.is_auto_generated,
    accountId: row.account_id ?? undefined,
    transferGroupId: row.transfer_group_id ?? undefined,
    linkedTransferGroupId: row.linked_transfer_group_id ?? undefined,
    metadata: normalizeMetadata(row.metadata),
    createdAt: normalizeIsoDate(row.created_at, row.transaction_at),
    updatedAt: normalizeIsoDate(row.updated_at, row.created_at),
    synced: row.synced,
  };
}

export function toAccount(row: AccountRow): Account {
  return {
    id: row.id,
    userId: row.user_id,
    name: row.name,
    type: normalizeAccountType(row.type),
    expensePaymentMethod: row.expense_payment_method ?? undefined,
    initialBalance: toNumber(row.initial_balance),
    color: row.color ?? undefined,
    icon: row.icon ?? undefined,
    isSystemCashWallet: Boolean(row.is_system_cash_wallet),
    isArchived: row.is_archived,
    createdAt: normalizeIsoDate(row.created_at, row.created_at),
    updatedAt: normalizeIsoDate(row.updated_at, row.updated_at),
  };
}

export function toBudget(row: BudgetRow): Budget {
  const alertThresholdsTriggered = Array.isArray(row.alert_thresholds_triggered)
    ? row.alert_thresholds_triggered.slice().sort((a, b) => a - b)
    : [];

  return {
    id: row.id,
    category: row.category,
    subCategory: row.sub_category ?? undefined,
    monthlyLimit: toNumber(row.monthly_limit),
    month: dateToMonth(row.budget_month),
    rollover: row.rollover,
    alertThresholdsTriggered,
  };
}

export function toSavingsGoal(row: SavingsGoalRow): SavingsGoal {
  return {
    id: row.id,
    userId: row.user_id,
    name: row.name,
    emoji: row.emoji,
    colorAccent: row.color_accent,
    tag: row.tag ?? undefined,
    motivationNote: row.motivation_note ?? undefined,
    targetAmount: toNumber(row.target_amount),
    currentAmount: toNumber(row.current_amount),
    deadline: row.deadline ?? undefined,
    isPrivate: row.is_private,
    isPinned: row.is_pinned,
    sortOrder: row.sort_order,
    status: row.status,
    completedAt: row.completed_at ?? undefined,
    whatDidYouBuy: row.what_did_you_buy ?? undefined,
    createdAt: normalizeIsoDate(row.created_at, row.created_at),
    updatedAt: normalizeIsoDate(row.updated_at, row.created_at),
  };
}

export function toSavingsDeposit(row: SavingsDepositRow): SavingsDeposit {
  return {
    id: row.id,
    goalId: row.goal_id,
    userId: row.user_id,
    amount: toNumber(row.amount),
    type: row.type,
    note: row.note ?? undefined,
    createdAt: normalizeIsoDate(row.created_at, row.created_at),
  };
}

export function toExternalWithdrawalRequest(
  row: ExternalWithdrawalRequestRow
): ExternalWithdrawalRequest {
  return {
    id: row.id,
    userId: row.user_id,
    fromAccountId: row.from_account_id,
    amount: toNumber(row.amount),
    feeAmount: toNumber(row.fee_amount),
    netAmount: toNumber(row.net_amount),
    destinationSummary: row.destination_summary,
    status: row.status,
    providerRef: row.provider_ref ?? undefined,
    etaAt: row.eta_at ? normalizeIsoDate(row.eta_at, row.eta_at) : undefined,
    idempotencyKey: row.idempotency_key,
    failureReason: row.failure_reason ?? undefined,
    completedTransactionId: row.completed_transaction_id ?? undefined,
    metadata: normalizeMetadata(row.metadata),
    createdBy: row.created_by ?? undefined,
    createdAt: normalizeIsoDate(row.created_at, row.created_at),
    updatedAt: normalizeIsoDate(row.updated_at, row.updated_at),
  };
}
