import type { SupabaseClient } from '@supabase/supabase-js';

import type { RecurringConfig, Transaction, TransactionSplit } from '../types';
import { toTransaction } from './mappers';
import { normalizeIncomeCategory, normalizeTransactionType } from './normalizers';
import { LEGACY_TRANSACTION_SELECT, TRANSACTION_SELECT } from './selects';
import type { TransactionRow } from './rows';
import { isMissingAccountsSchemaError, normalizeIsoDate, throwIfError } from './shared';

export function toTransactionInsertPayload(tx: Transaction, userId: string) {
  const type = normalizeTransactionType(tx.type);
  const incomeCategory =
    type === 'income'
      ? normalizeIncomeCategory(tx.incomeCategory) ??
        normalizeIncomeCategory(tx.subCategory) ??
        'Other Income'
      : undefined;
  const persistedSubCategory = type === 'income' ? incomeCategory : tx.subCategory ?? null;
  const fallbackDescription =
    tx.description || tx.notes || (type === 'income' ? incomeCategory || tx.category : tx.category);

  return {
    id: tx.id,
    user_id: userId,
    amount: Number(tx.amount.toFixed(2)),
    type,
    category: tx.category,
    sub_category: persistedSubCategory,
    merchant: tx.merchant ?? null,
    description: fallbackDescription,
    transaction_at: normalizeIsoDate(tx.date, new Date().toISOString()),
    payment_method: tx.paymentMethod,
    notes: tx.notes || '',
    tags: Array.isArray(tx.tags) ? tx.tags : [],
    attachment_base64: tx.attachmentBase64 ?? null,
    savings_meta: tx.savingsMeta ?? null,
    recurring_frequency: tx.recurring?.frequency ?? null,
    recurring_interval: tx.recurring ? Math.max(1, Math.floor(tx.recurring.interval || 1)) : null,
    recurring_next_run_at: tx.recurring?.nextRunDate ?? null,
    recurring_end_at: tx.recurring?.endDate ?? null,
    recurring_origin_id: tx.recurringOriginId ?? null,
    is_auto_generated: Boolean(tx.isAutoGenerated),
    account_id: tx.accountId ?? null,
    transfer_group_id: tx.transferGroupId ?? null,
    linked_transfer_group_id: tx.linkedTransferGroupId ?? null,
    metadata: tx.metadata ?? {},
    synced: typeof tx.synced === 'boolean' ? tx.synced : true,
    created_at: normalizeIsoDate(tx.createdAt, new Date().toISOString()),
    updated_at: normalizeIsoDate(tx.updatedAt, tx.createdAt || new Date().toISOString()),
  };
}

export function toRecurringUpdatePayload(recurring: RecurringConfig | undefined) {
  if (!recurring) {
    return {
      recurring_frequency: null,
      recurring_interval: null,
      recurring_next_run_at: null,
      recurring_end_at: null,
    };
  }

  return {
    recurring_frequency: recurring.frequency,
    recurring_interval: Math.max(1, Math.floor(recurring.interval || 1)),
    recurring_next_run_at: normalizeIsoDate(recurring.nextRunDate, new Date().toISOString()),
    recurring_end_at: recurring.endDate
      ? normalizeIsoDate(recurring.endDate, recurring.endDate)
      : null,
  };
}

export async function getTransactionById(
  supabase: SupabaseClient,
  id: string
): Promise<Transaction | null> {
  let { data, error } = await supabase
    .from('transactions')
    .select(TRANSACTION_SELECT)
    .eq('id', id)
    .maybeSingle();

  if (error && isMissingAccountsSchemaError(error)) {
    const fallback = await supabase
      .from('transactions')
      .select(LEGACY_TRANSACTION_SELECT)
      .eq('id', id)
      .maybeSingle();
    data = fallback.data as typeof data;
    error = fallback.error;
  }

  throwIfError('Failed to fetch transaction', error);

  if (!data) {
    return null;
  }

  return toTransaction(data as TransactionRow);
}

export async function replaceTransactionSplits(
  supabase: SupabaseClient,
  transactionId: string,
  split: TransactionSplit[] | undefined
): Promise<void> {
  const payload = Array.isArray(split)
    ? split.map((line) => ({
        id: line.id,
        category: line.category,
        subCategory: line.subCategory ?? null,
        amount: Number(line.amount.toFixed(2)),
      }))
    : [];

  const { error } = await supabase.rpc('replace_transaction_splits', {
    p_transaction_id: transactionId,
    p_splits: payload,
  });

  throwIfError('Failed to write transaction splits', error);
}
